[package]
name = "crossbtc-vaults"
version = "0.1.0"
description = "Cross-chain Bitcoin yield vault smart contracts"

[dependencies]
starknet = "2.6.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.9.0" }

[[target.starknet-contract]]
sierra = true
casm = true